### ISSUE TITLE
Cannot build on CloudPebble

### ISSUE THREAD

**Issue by m0urs** [jamesfairhurst/Pebbos#6]
Hi,

I tried to build that app with CloudPebble. However the build fails with the following errors:

[15/40] c: src/js/simply/simply_accel.c -> build/src/js/simply/simply_accel.c.12.o
In file included from ../src/js/simply/simply_window.c:10:0:
/tmp/tmpGJOsdW/src/util/graphics.h: In function 'gbitmap_is_palette_black_and_white':
/tmp/tmpGJOsdW/src/util/graphics.h:42:3: error: implicit declaration of function 'gbitmap_get_format' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
In file included from ../src/simply/simply_window.c:10:0:
/tmp/tmpGJOsdW/src/util/graphics.h: In function 'gbitmap_is_palette_black_and_white':
/tmp/tmpGJOsdW/src/util/graphics.h:42:3: error: implicit declaration of function 'gbitmap_get_format' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
Waf: Leaving directory `/tmp/tmpGJOsdW/build'
Build failed
 -> task in 'aplite/pebble-app.elf' failed (exit status 1): 
    {task 140013701284752: c simply_window.c -> simply_window.c.12.o}
['arm-none-eabi-gcc', '-std=c99', '-mcpu=cortex-m3', '-mthumb', '-ffunction-sections', '-fdata-sections', '-g', '-Os', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter', '-Wno-error=unused-function', '-Wno-error=unused-variable', '-Wno-address', '-Wno-type-limits', '-Wno-missing-field-initializers', '-fPIE', '-I/tmp/app/sdk2/Pebble/include', '-I/app/sdk2/Pebble/include', '-I/tmp/tmpGJOsdW/build', '-I/tmp/tmpGJOsdW', '-I/tmp/tmpGJOsdW/build/src', '-I/tmp/tmpGJOsdW/src', '-DRELEASE', '-D__FILE_NAME__="simply_window.c"', '../src/js/simply/simply_window.c', '-c', '-o', 'src/js/simply/simply_window.c.12.o']
 -> task in 'aplite/pebble-app.elf' failed (exit status 1): 
    {task 140013701286544: c simply_window.c -> simply_window.c.12.o}
['arm-none-eabi-gcc', '-std=c99', '-mcpu=cortex-m3', '-mthumb', '-ffunction-sections', '-fdata-sections', '-g', '-Os', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter', '-Wno-error=unused-function', '-Wno-error=unused-variable', '-Wno-address', '-Wno-type-limits', '-Wno-missing-field-initializers', '-fPIE', '-I/tmp/app/sdk2/Pebble/include', '-I/app/sdk2/Pebble/include', '-I/tmp/tmpGJOsdW/build', '-I/tmp/tmpGJOsdW', '-I/tmp/tmpGJOsdW/build/src', '-I/tmp/tmpGJOsdW/src', '-DRELEASE', '-D__FILE_NAME__="simply_window.c"', '../src/simply/simply_window.c', '-c', '-o', 'src/simply/simply_window.c.12.o']
[ERROR   ] A compilation error occurred

As I am not a eveloper but just wanted to build that app I have no glue where the problem is. Could you help me?

Thanks a lot
Michael

**Comment by jamesfairhurst** [comment]
Hmm not sure about this, seems like an issue with the SDK, will have to check on my laptop if it still compiles when I get a spare moment.

**Comment by m0urs** [comment]
James, not so urgent. Thanks. In the meantime I found out that there is already a compiled version in the Pebble app store :-) So no need to compile it by myself ...

**Comment by jamesfairhurst** [comment]
Yes! Should of led with that :)
