### ISSUE TITLE
find my sonos speaker failed.

### ISSUE THREAD

**Issue by iyoukeyyewei** [jamesfairhurst/Pebbos#7]
set the correct ip address. but it is still cannot find my sonos player 3.

**Comment by jamesfairhurst** [comment]
Is it grouped or have a name with non-alphanumeric characters?

**Comment by iyoukeyyewei** [comment]
it's the only speaker. The zone name is in Chinese.. Tried to rename the Zone name to English. Still cannot find the speaker.
